#!/bin/bash

# Get the script directory path
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
CONFIG_FILE="$SCRIPT_DIR/clickup_config.sh"

# Banner
echo "======================================"
echo "   ClickUp Git Integration Setup"
echo "======================================"
echo

# Check if configuration file already exists
if [ -f "$CONFIG_FILE" ]; then
    echo "Configuration file already exists at: $CONFIG_FILE"
    read -p "Do you want to reconfigure? (y/n): " reconfigure
    if [[ ! "$reconfigure" =~ ^[Yy]$ ]]; then
        echo "Setup canceled. Using existing configuration."
        exit 0
    fi
fi

# Get ClickUp API information
echo "Please enter your ClickUp API information:"
echo "(This information will be stored locally and never shared)"
echo

# API Key with masked input for security
read -p "ClickUp API Key: " api_key
if [ -z "$api_key" ]; then
    echo "Error: API Key is required."
    exit 1
fi

# Ask for Workspace and Space IDs
read -p "Workspace ID: " workspace_id
if [ -z "$workspace_id" ]; then
    echo "Error: Wrokspace ID is required."
    exit 1
fi

read -p "Space ID: " space_id
if [ -z "$space_id" ]; then
    echo "Error: Space ID is required."
    exit 1
fi

# Ask for default status
read -p "Default status for new subtasks [IN DEVELOPMENT]: " default_status
default_status=${default_status:-"IN DEVELOPMENT"}

# Write configuration to file with restricted permissions
cat > "$CONFIG_FILE" << EOF
#!/bin/bash
# ClickUp API Configuration
# Generated on $(date)
# WARNING: This file contains sensitive information - do not commit to version control

# API Settings
CLICKUP_API_URL="https://api.clickup.com/api/v2"
CLICKUP_API_KEY="$api_key"
CLICKUP_DEFAULT_STATUS="$default_status"
WORKSPACE_ID="$workspace_id"
SPACE_ID="$space_id"
EOF

# Set permissions to restrict access to the owner only
chmod 600 "$CONFIG_FILE"

echo
echo "Configuration saved to: $CONFIG_FILE"
echo "File permissions set to owner-only access (600)"
echo

# Create .gitignore if it doesn't exist and add config file
GITIGNORE_FILE="$SCRIPT_DIR/../.gitignore"
if [ ! -f "$GITIGNORE_FILE" ]; then
    echo "# Generated by ClickUp setup" > "$GITIGNORE_FILE"
fi

# Check if config file is already in .gitignore
if ! grep -q "clickup_config.sh" "$GITIGNORE_FILE"; then
    echo "# ClickUp configuration (contains sensitive data)" >> "$GITIGNORE_FILE"
    echo ".clickup-automation/clickup_config.sh" >> "$GITIGNORE_FILE"
    echo "Added configuration file to .gitignore for security"
fi

echo
echo "Setup completed successfully!"
echo "To change configuration in the future, run this setup script again or edit:"
echo "$CONFIG_FILE"
echo
